### ISSUE TITLE
Question : thrust control 

### ISSUE THREAD

**Issue by hajuny** [rtatze/JSBSim_gym_wrapper#2]
hi.  

I'm studying reinforcement learning in graduate school. 
My area of interest is aircraft reinforcement learning and transfer learning.
so, thank you so much for your work. 

I was trying to control the aircraft using your work.
but , aircraft altitude is not maintained. 
The altitude drops even when the throttle is set to 1 in the action. 

<img src ="https://i.imgur.com/h0iHL2k.png">

<img src="https://i.imgur.com/nNJ0nlN.png">

blue action : throttle 1, aileron 0, elevator 0
red action : random 

Both aircraft dive sharply and collide with the ground.

There seems to be no thrust response to the throttle, is there any way to fix it?

One more question, can the aircraft use all the aircraft in jsbsim?

**Comment by rtatze** [comment]
Hi,
i will add some init props...
maybe you can start with:

sim.set_properties('propulsion/starter_cmd', 1)
sim.set_properties('propulsion/engine/set-running', 1)
sim.set_properties('fcs/throttle-cmd-norm', 1.0)

then you can check if there are rpm:

sim.get_properties('propulsion/engine/propeller-rpm')

2. with the config.toml file you can change the ac
